[parse]
# Whether to parse dependent crates and include their types in the generated
# bindings
parse_deps = true
# A black list of crate names that are not allowed to be parsed
exclude = ["libc", "lua_jit_sys"]